"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Footer from "./components/Footer";
import Nav from "./components/Nav";

// const theme = createTheme({
//   palette: {
//     primary: {
//       main: "#fffff",
//     },
//     secondary: {
//       main: "#414141",
//     },
//   },
// });
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const bodyStyle = {
  minHeight: "calc(100vh - 180px)",
};
const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className} style={bodyStyle}>
        <Nav />
        {children}

        <Footer />
      </body>
    </html>
  );
}
